export const REGIONS = [
  { id: "north", label: "北區", short: "北" },
  { id: "tyhcm", label: "桃竹苗", short: "桃竹苗" },
  { id: "central", label: "中部", short: "中" },
  { id: "south", label: "南部", short: "南" },
  { id: "east", label: "東部", short: "東" },
];

export const stores = [
  {
    id: "nanxi-skm",
    name: "三越南西",
    region: "north",
    city: "台北市",
    mall: "新光三越台北南西店",
    facebook: "https://www.facebook.com/share/1BuSqwADRT/",
    line: "https://line.me/R/ti/p/@626iceit",
    lat: 25.05236,
    lng: 121.52025,
  },
  {
    id: "tianmu-sogo",
    name: "天母SOGO",
    region: "north",
    city: "台北市",
    mall: "天母SOGO",
    facebook: "https://www.facebook.com/profile.php?id=61592597564673",
    line: "https://line.me/R/ti/p/@377cbfue",
    lat: 25.11836,
    lng: 121.53148,
  },
  {
    id: "breeze-plaza",
    name: "比漾廣場",
    region: "north",
    city: "新北市",
    mall: "比漾廣場",
    facebook: "https://www.facebook.com/profile.php?id=61592677934745",
    line: "https://line.me/R/ti/p/@ufq5307a",
    lat: 25.00845,
    lng: 121.51512,
  },
  {
    id: "miramar",
    name: "美麗華",
    region: "north",
    city: "台北市",
    mall: "美麗華百樂園",
    facebook: "https://www.facebook.com/profile.php?id=61592730395195",
    line: "https://line.me/R/ti/p/@660hextn",
    lat: 25.08347,
    lng: 121.55738,
  },
  {
    id: "banqiao-feds",
    name: "板橋遠東",
    region: "north",
    city: "新北市",
    mall: "遠東百貨板橋店",
    facebook: "https://www.facebook.com/share/1BmnHxAaZ7/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@083zoknr",
    lat: 25.01105,
    lng: 121.46218,
  },
  {
    id: "zhonghe-global",
    name: "中和環球",
    region: "north",
    city: "新北市",
    mall: "環球購物中心中和店",
    facebook: "https://www.facebook.com/profile.php?id=61575325211390&locale=zh_TW",
    line: "https://line.me/R/ti/p/@zgq9395a",
    lat: 25.00655,
    lng: 121.48495,
  },
  {
    id: "banqiao-mega",
    name: "板橋大遠百",
    region: "north",
    city: "新北市",
    mall: "大遠百板橋店",
    facebook: "https://www.facebook.com/profile.php?id=61584956488867",
    line: "https://line.me/R/ti/p/@585clqqg",
    lat: 25.01442,
    lng: 121.46638,
  },
  {
    id: "xike-farglory",
    name: "汐科遠雄",
    region: "north",
    city: "新北市",
    mall: "遠雄U-TOWN",
    facebook: "https://www.facebook.com/profile.php?id=61592991209842",
    line: "https://line.me/R/ti/p/@mhb3876c",
    lat: 25.06205,
    lng: 121.64815,
  },
  {
    id: "shulin-showtime",
    name: "樹林秀泰",
    region: "north",
    city: "新北市",
    mall: "樹林秀泰廣場",
    facebook: "https://www.facebook.com/profile.php?id=61591486063647",
    line: "https://line.me/R/ti/p/@046txnme",
    lat: 24.99152,
    lng: 121.42405,
  },
  {
    id: "tamsui-lai",
    name: "淡水禮萊廣場",
    region: "north",
    city: "新北市",
    mall: "淡水禮萊廣場",
    facebook: "https://www.facebook.com/share/1Db8rVD6Hk/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@944creff",
    lat: 25.16918,
    lng: 121.44385,
  },
  {
    id: "honhui",
    name: "宏匯廣場",
    region: "north",
    city: "新北市",
    mall: "宏匯廣場",
    facebook: "https://www.facebook.com/funbox.honhui",
    line: "https://line.me/R/ti/p/@513vgbqo",
    lat: 25.06012,
    lng: 121.45935,
  },
  {
    id: "xindian-yulon",
    name: "新店裕隆城",
    region: "north",
    city: "新北市",
    mall: "新店裕隆城",
    facebook: "https://www.facebook.com/share/19E9UZWhK9/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@491uicsm",
    lat: 24.97275,
    lng: 121.54122,
  },
  {
    id: "nangang-lalaport",
    name: "南港LaLaport",
    region: "north",
    city: "台北市",
    mall: "三井LaLaport南港",
    facebook: "http://www.facebook.com/share/14jPaVWXoLJ/?mibextid=wwXlfr",
    line: "https://line.me/R/ti/p/@924ngwfb",
    lat: 25.05948,
    lng: 121.61482,
  },
  {
    id: "zhongxiao-sogo",
    name: "台北忠孝遠東SOGO",
    region: "north",
    city: "台北市",
    mall: "忠孝SOGO",
    facebook: "https://www.facebook.com/funboxsogo",
    line: "https://line.me/R/ti/p/@lcn7452p",
    lat: 25.04172,
    lng: 121.54485,
  },
  {
    id: "station-skm",
    name: "三越站前",
    region: "north",
    city: "台北市",
    mall: "新光三越台北站前店",
    facebook: "https://www.facebook.com/profile.php?id=61593176934292",
    line: "https://line.me/R/ti/p/@631ovgxp",
    lat: 25.04618,
    lng: 121.51582,
  },
  {
    id: "takashimaya",
    name: "高島屋百貨",
    region: "north",
    city: "台北市",
    mall: "台北高島屋",
    facebook: "https://www.facebook.com/ybg5152n",
    line: "https://line.me/R/ti/p/@xbm4599s",
    lat: 25.03862,
    lng: 121.56742,
  },
  {
    id: "xinyi-a8",
    name: "信義新天地A8館",
    region: "north",
    city: "台北市",
    mall: "新光三越信義新天地A8",
    facebook: "https://www.facebook.com/profile.php?id=61593106704912&locale=zh_TW",
    line: "https://line.me/R/ti/p/@983dfazy",
    lat: 25.03942,
    lng: 121.56672,
  },
  {
    id: "nangang-station",
    name: "潤泰南港車站店",
    region: "north",
    city: "台北市",
    mall: "南港車站",
    facebook: "https://www.facebook.com/profile.php?id=61592736394851",
    line: "https://line.me/R/ti/p/@924tguor",
    lat: 25.05228,
    lng: 121.60662,
  },
  {
    id: "tianmu-skm",
    name: "天母三越",
    region: "north",
    city: "台北市",
    mall: "新光三越天母店",
    facebook: "https://www.facebook.com/share/1K6XRBMujq/",
    line: "https://line.me/R/ti/p/@237annfd",
    lat: 25.11962,
    lng: 121.53222,
  },
  {
    id: "xinyi-a13",
    name: "遠百信義A13",
    region: "north",
    city: "台北市",
    mall: "遠東百貨信義A13",
    facebook: "https://www.facebook.com/profile.php?id=61551944767554",
    line: "https://line.me/R/ti/p/@020sqlyp",
    lat: 25.03822,
    lng: 121.56818,
  },
  {
    id: "taoyuan-station",
    name: "桃園站前",
    region: "tyhcm",
    city: "桃園市",
    mall: "新光三越桃園站前店",
    facebook: "https://www.facebook.com/profile.php?id=100064059014450",
    line: "https://line.me/R/ti/p/@fcm1241y",
    lat: 24.98942,
    lng: 121.31138,
  },
  {
    id: "taoyuan-a19",
    name: "桃園環球A19",
    region: "tyhcm",
    city: "桃園市",
    mall: "環球購物中心桃園A19",
    facebook: "https://www.facebook.com/profile.php?id=100083960592067",
    line: "https://line.me/R/ti/p/@403qwxdn",
    lat: 25.01328,
    lng: 121.21335,
  },
  {
    id: "hsinchu-feds",
    name: "新竹遠東",
    region: "tyhcm",
    city: "新竹市",
    mall: "遠東百貨新竹店",
    facebook: "https://www.facebook.com/profile.php?id=61591842121755",
    line: "https://line.me/R/ti/p/@822rfnmr",
    lat: 24.80192,
    lng: 120.96642,
  },
  {
    id: "zhongli-sogo",
    name: "中壢SOGO",
    region: "tyhcm",
    city: "桃園市",
    mall: "中壢SOGO",
    facebook: "https://www.facebook.com/profile.php?id=61558958859748",
    line: "https://line.me/R/ti/p/@xcs3672w",
    lat: 24.95782,
    lng: 121.22538,
  },
  {
    id: "hsinchu-nanya",
    name: "新竹遠雄湳雅",
    region: "tyhcm",
    city: "新竹市",
    mall: "遠雄湳雅廣場",
    facebook: "https://www.facebook.com/profile.php?id=61592712696197",
    line: "https://line.me/R/ti/p/@agl4214l",
    lat: 24.79685,
    lng: 121.01842,
  },
  {
    id: "taoyuan-feds",
    name: "桃園遠東",
    region: "tyhcm",
    city: "桃園市",
    mall: "遠東百貨桃園店",
    facebook: "https://www.facebook.com/profile.php?id=100064240476385",
    line: "https://line.me/R/ti/p/@bix0595a",
    lat: 24.99082,
    lng: 121.31322,
  },
  {
    id: "taimall",
    name: "台茂購物中心",
    region: "tyhcm",
    city: "桃園市",
    mall: "台茂購物中心",
    facebook: "https://www.facebook.com/profile.php?id=61590975990981&locale=zh_TW",
    line: "https://line.me/R/ti/p/@504tdsbb",
    lat: 25.05382,
    lng: 121.28822,
  },
  {
    id: "taoyuan-a8",
    name: "桃園環球A8",
    region: "tyhcm",
    city: "桃園市",
    mall: "環球購物中心桃園A8",
    facebook: "https://www.facebook.com/profile.php?id=61591728303067",
    line: "https://line.me/R/ti/p/@lae4656h",
    lat: 25.06042,
    lng: 121.36522,
  },
  {
    id: "zhongli-taijiang",
    name: "中壢大江",
    region: "tyhcm",
    city: "桃園市",
    mall: "大江國際購物中心",
    facebook: "https://www.facebook.com/profile.php?id=100063657227053",
    line: "https://line.me/R/ti/p/@099ldnvw",
    lat: 24.97352,
    lng: 121.25522,
  },
  {
    id: "hsinchu-bigcity",
    name: "新竹巨城",
    region: "tyhcm",
    city: "新竹市",
    mall: "新竹巨城",
    facebook: "https://www.facebook.com/share/1D2TZJ7pr3/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@532otwmb",
    lat: 24.80972,
    lng: 120.97542,
  },
  {
    id: "zhubei-feds",
    name: "竹北遠東",
    region: "tyhcm",
    city: "新竹縣",
    mall: "遠東百貨竹北店",
    facebook: "https://www.facebook.com/ZhubeiFunbox/?locale=zh_TW",
    line: "https://line.me/R/ti/p/@642vdyvq",
    lat: 24.83482,
    lng: 121.01282,
  },
  {
    id: "hsinchu-park",
    name: "新竹享平方",
    region: "tyhcm",
    city: "新竹市",
    mall: "享平方",
    facebook: "https://www.facebook.com/share/193j7smii9/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@062qoqex",
    lat: 24.80492,
    lng: 120.99252,
  },
  {
    id: "miaoli-shangshun",
    name: "苗栗尚順",
    region: "tyhcm",
    city: "苗栗縣",
    mall: "尚順購物中心",
    facebook: "https://www.facebook.com/share/1DZmr5Njyk/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@185vowmo",
    lat: 24.68682,
    lng: 120.89382,
  },
  {
    id: "taichung-chungyo",
    name: "台中中友",
    region: "central",
    city: "台中市",
    mall: "中友百貨",
    facebook:
      "https://www.facebook.com/p/Funbox-%E5%8F%B0%E4%B8%AD%E4%B8%AD%E5%8F%8B-100063893358626/",
    line: "https://line.me/R/ti/p/@815dstuy",
    lat: 24.15218,
    lng: 120.68472,
  },
  {
    id: "taichung-feds",
    name: "台中遠東",
    region: "central",
    city: "台中市",
    mall: "大遠百台中店",
    facebook: "https://www.facebook.com/share/1EZCDU6tF1/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@147vfxjr",
    lat: 24.16385,
    lng: 120.64012,
  },
  {
    id: "kuangsan-sogo",
    name: "廣三SOGO",
    region: "central",
    city: "台中市",
    mall: "廣三SOGO",
    facebook: "https://www.facebook.com/share/1JaCvYo7ao/",
    line: "https://line.me/R/ti/p/@526bsjmb",
    lat: 24.15512,
    lng: 120.65305,
  },
  {
    id: "taichung-skm",
    name: "台中三越",
    region: "central",
    city: "台中市",
    mall: "新光三越台中中港店",
    facebook: "https://www.facebook.com/profile.php?id=61591770278850&locale=zh_TW",
    line: "https://line.me/R/ti/p/@833rhkmr",
    lat: 24.16482,
    lng: 120.64355,
  },
  {
    id: "taichung-newera",
    name: "台中新時代",
    region: "central",
    city: "台中市",
    mall: "台中新時代購物中心",
    facebook: "https://www.facebook.com/share/1J3PLMbDSN/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@hdg3289a",
    lat: 24.13785,
    lng: 120.68652,
  },
  {
    id: "taichung-hanshin",
    name: "台中漢神洲際",
    region: "central",
    city: "台中市",
    mall: "漢神洲際購物中心",
    facebook: "https://www.facebook.com/profile.php?id=61592777043158",
    line: "https://line.me/R/ti/p/@218xxrbx",
    lat: 24.18548,
    lng: 120.64605,
  },
  {
    id: "wenxin-showtime",
    name: "文心秀泰",
    region: "central",
    city: "台中市",
    mall: "文心秀泰廣場",
    facebook: "https://www.facebook.com/share/19F2BoUzUv/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@605dilqq",
    lat: 24.15055,
    lng: 120.64622,
  },
  {
    id: "fengyuan-pacific",
    name: "豐原太平洋",
    region: "central",
    city: "台中市",
    mall: "豐原太平洋百貨",
    facebook: "https://www.facebook.com/profile.php?id=61592589610506",
    line: "https://line.me/R/ti/p/@094mvrhb",
    lat: 24.25182,
    lng: 120.72105,
  },
  {
    id: "taichung-port-mitsui",
    name: "台中港三井",
    region: "central",
    city: "台中市",
    mall: "三井Outlet台中港",
    facebook: "https://www.facebook.com/share/1Jj8ybhtUR/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@816xpruh",
    lat: 24.25652,
    lng: 120.53215,
  },
  {
    id: "lihpao",
    name: "麗寶一期",
    region: "central",
    city: "台中市",
    mall: "麗寶Outlet Mall",
    facebook: "https://www.facebook.com/profile.php?id=61592814215979&locale=zh_TW",
    line: "https://line.me/R/ti/p/@829adhop",
    lat: 24.32322,
    lng: 120.69852,
  },
  {
    id: "taichung-lalaport",
    name: "台中Lalaport",
    region: "central",
    city: "台中市",
    mall: "三井LaLaport台中",
    facebook: "https://www.facebook.com/profile.php?id=61591544926718",
    line: "https://line.me/R/ti/p/@620dfrfm",
    lat: 24.13722,
    lng: 120.69952,
  },
  {
    id: "kaohsiung-hanshin",
    name: "高雄漢神",
    region: "south",
    city: "高雄市",
    mall: "漢神百貨",
    facebook: "https://www.facebook.com/share/1LrCbM7p9k/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@897upgfr",
    lat: 22.61952,
    lng: 120.29648,
  },
  {
    id: "hanshin-arena",
    name: "漢神巨蛋",
    region: "south",
    city: "高雄市",
    mall: "漢神巨蛋購物廣場",
    facebook: "https://www.facebook.com/share/1JMvwfTqpu/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@ldh6278d",
    lat: 22.66948,
    lng: 120.30205,
  },
  {
    id: "kaohsiung-zuoying",
    name: "高雄左營",
    region: "south",
    city: "高雄市",
    mall: "新光三越高雄左營店",
    facebook: "https://www.facebook.com/100057115973730/",
    line: "https://line.me/R/ti/p/@obz8096L",
    lat: 22.68705,
    lng: 120.30952,
  },
  {
    id: "dream-mall",
    name: "夢時代二館",
    region: "south",
    city: "高雄市",
    mall: "夢時代購物中心",
    facebook: "https://www.facebook.com/share/1iiWSKHcvP/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@ott3541o",
    lat: 22.59548,
    lng: 120.30685,
  },
  {
    id: "pingtung-global",
    name: "屏東環球",
    region: "south",
    city: "屏東縣",
    mall: "環球購物中心屏東店",
    facebook: "https://m.facebook.com/profile.php?id=61591804545442",
    line: "https://line.me/R/ti/p/@xhi2668e",
    lat: 22.66852,
    lng: 120.48605,
  },
  {
    id: "kaohsiung-dali",
    name: "高雄大立",
    region: "south",
    city: "高雄市",
    mall: "大立百貨",
    facebook: "https://www.facebook.com/share/1CLmgDDbFw/",
    line: "https://line.me/R/ti/p/@917hatdy",
    lat: 22.62048,
    lng: 120.29452,
  },
  {
    id: "i-ride",
    name: "義享天地",
    region: "south",
    city: "高雄市",
    mall: "義享天地",
    facebook: "https://www.facebook.com/share/1EGnZY5Wad/",
    line: "https://line.me/R/ti/p/@777nkbeo",
    lat: 22.65692,
    lng: 120.29385,
  },
  {
    id: "chiayi-feds",
    name: "嘉義遠東",
    region: "south",
    city: "嘉義市",
    mall: "遠東百貨嘉義店",
    facebook: "https://www.facebook.com/profile.php?id=61592768918548",
    line: "https://line.me/R/ti/p/@gno1826d",
    lat: 23.47922,
    lng: 120.44122,
  },
  {
    id: "chiayi-nice",
    name: "嘉義耐斯",
    region: "south",
    city: "嘉義市",
    mall: "耐斯廣場",
    facebook: "https://www.facebook.com/profile.php?id=61591841012874",
    line: "https://line.me/R/ti/p/@121vsdww",
    lat: 23.48722,
    lng: 120.45352,
  },
  {
    id: "chiayi-skm",
    name: "嘉義三越",
    region: "south",
    city: "嘉義市",
    mall: "新光三越嘉義垂楊店",
    facebook: "https://www.facebook.com/share/1ELX2AJ1ue/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@zhj4962p",
    lat: 23.47482,
    lng: 120.44922,
  },
  {
    id: "kaohsiung-sogo",
    name: "崇光高雄",
    region: "south",
    city: "高雄市",
    mall: "高雄SOGO",
    facebook: "https://www.facebook.com/share/19E7invurA/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@845nallq",
    lat: 22.61482,
    lng: 120.30622,
  },
  {
    id: "kaohsiung-mega",
    name: "高雄大遠百",
    region: "south",
    city: "高雄市",
    mall: "大遠百高雄店",
    facebook: "https://www.facebook.com/share/1Asnih4jRc/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@204edsnm",
    lat: 22.61352,
    lng: 120.30452,
  },
  {
    id: "edda-2",
    name: "義大二館",
    region: "south",
    city: "高雄市",
    mall: "義大世界購物廣場二館",
    facebook: "https://www.facebook.com/share/1BwVM2Q3UP",
    line: "https://line.me/R/ti/p/@bxd6822t",
    lat: 22.72982,
    lng: 120.40482,
  },
  {
    id: "taroko-skm",
    name: "大魯閣新光",
    region: "south",
    city: "高雄市",
    mall: "大魯閣草衙道",
    facebook: "https://www.facebook.com/share/1EhNbSScWd/",
    line: "https://line.me/R/ti/p/@fko7562c",
    lat: 22.58152,
    lng: 120.33322,
  },
  {
    id: "tainan-feds",
    name: "台南遠百",
    region: "south",
    city: "台南市",
    mall: "遠東百貨台南成功店",
    facebook: "https://www.facebook.com/share/19JiPRLTe3/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@373rxyat",
    lat: 22.99262,
    lng: 120.20982,
  },
  {
    id: "tainan-ximen",
    name: "台南西門",
    region: "south",
    city: "台南市",
    mall: "新光三越台南西門店",
    facebook: "https://www.facebook.com/share/1EgGWhL2my/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@344rybaf",
    lat: 22.99652,
    lng: 120.19782,
  },
  {
    id: "tainan-nanfang",
    name: "南紡購物中心",
    region: "south",
    city: "台南市",
    mall: "南紡購物中心",
    facebook: "https://www.facebook.com/profile.php?id=100057043616291",
    line: "https://line.me/R/ti/p/@msq0107x",
    lat: 22.99182,
    lng: 120.23352,
  },
  {
    id: "tainan-mitsui",
    name: "台南三井",
    region: "south",
    city: "台南市",
    mall: "三井Outlet台南",
    facebook: "https://www.facebook.com/share/1981qXi5wG/",
    line: "https://line.me/R/ti/p/@212isujx",
    lat: 22.92482,
    lng: 120.28552,
  },
  {
    id: "pingtung-pacific",
    name: "屏東太平洋",
    region: "south",
    city: "屏東縣",
    mall: "太平洋百貨屏東店",
    facebook: "https://www.facebook.com/share/1bsqHbH5yg/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@ess7711t",
    lat: 22.67322,
    lng: 120.48882,
  },
  {
    id: "penghu-pengfang",
    name: "澎坊商場",
    region: "south",
    city: "澎湖縣",
    mall: "澎坊商場",
    facebook: "https://www.facebook.com/share/1G6GUr5oYt/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@185ybuaz",
    lat: 23.56582,
    lng: 119.56622,
  },
  {
    id: "yilan-luna",
    name: "新月廣場",
    region: "east",
    city: "宜蘭縣",
    mall: "宜蘭新月廣場",
    facebook: "https://www.facebook.com/funboxtoyluna/",
    line: "https://line.me/R/ti/p/@027iendl",
    lat: 24.75405,
    lng: 121.75312,
  },
  {
    id: "hualien-feds",
    name: "花蓮遠東",
    region: "east",
    city: "花蓮縣",
    mall: "遠東百貨花蓮店",
    facebook: "https://www.facebook.com/share/1Bq2zmw7FK/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@ymc0892z",
    lat: 23.97782,
    lng: 121.60522,
  },
  {
    id: "taitung-showtime",
    name: "台東秀泰",
    region: "east",
    city: "台東縣",
    mall: "台東秀泰廣場",
    facebook: "https://www.facebook.com/share/1BTxAEJsEC/?mibextid=wwXIfr",
    line: "https://line.me/R/ti/p/@438glrqv",
    lat: 22.75482,
    lng: 121.14622,
  },
];
